%{
#include 
%}

%token INT CONSTANT CHAR STRING NUMBER ID
%token IF ELSE WHILE FOR MAIN PRINTF END_OF_LINE
%token SEPARATOR BEGIN_PARENTHESIS END_PARENTHESIS BEGIN_BLOCK END_BLOCK
%token PLUS MINUS MULTIPLY DIVIDE EQUAL


